Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Role: arn:aws:iam::470384041006:role/uat-glue-role
      Name: uat-load-to-bronze
      Command:
        Name: glueetl
        ScriptLocation: s3://uat-bucket-tl/scripts/etl_job_uat.py
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-disable"
        "--glue-version": "4.0"
        "--worker-type": "G.1X"
        "--number-of-workers": "2"
        "--enable-auto-scaling": "true"
        "--job-language": "python3"   # Explicitly set to Python 3
        "--job-retries": "0"
        "--job-timeout": "2880"
      Connections:
        Connections:
          - Name: uat-redshift-connection
      ExecutionProperty:
        MaxConcurrentRuns: 1
