version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Testing Glue scripts..."
      - python -m py_compile scripts/*.py
      - echo "Testing SQL syntax..."
      - sqlfluff lint sql/*.sql || true
      - echo "Running orchestration..."
      - python scripts/orchestrate.py
artifacts:
  files:
    - scripts/*
    - sql/*
    - templates/*
